controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    joint6_controller:
      type: effort_controllers/JointEffortController
      joints:
        - junta_5_6
      pid:
        p: 10.0
        i: 0.1
        d: 0.01
