controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fake_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - junta_0_1
        - junta_1_2
        - junta_2_3
        - junta_3_4
        - junta_4_5
        - junta_5_6
      command_interfaces:
        - position
      state_interfaces:
        - position
